#pragma once

#include "NativeGameplayTags.h"

UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_Attack_Melee);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_Attack_Melee_Heavy);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_Attack_Projectile);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_Damage_Physical);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_Damage_Fire);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_Damage_Frost);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_Reaction_Hit);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_Reaction_Stagger);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_Reaction_Knockback);

UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_SpawnCompleted);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_TargetAcquired);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_TargetLost);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_PursuitResumed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_NavigationFailed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_AttackReady);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_Damaged);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_Killed);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_Recovered);
UE_DECLARE_GAMEPLAY_TAG_EXTERN(CombatTag_EnemyStateReason_Retired);
