#include "Core/GameLog.h"

DEFINE_LOG_CATEGORY(LogGame);
DEFINE_LOG_CATEGORY(LogBattle);
DEFINE_LOG_CATEGORY(LogHorde);
DEFINE_LOG_CATEGORY(LogBase);
DEFINE_LOG_CATEGORY(LogMeta);
DEFINE_LOG_CATEGORY(LogNetwork);
